# Generated by Django 5.1.1 on 2025-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_job_employee_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tracking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee')], max_length=30),
        ),
    ]
