# Generated by Django 5.1.1 on 2025-02-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_alter_profile_cv_alter_profile_skils_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skils',
            new_name='skills',
        ),
    ]
