# Generated by Django 5.1.1 on 2025-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_rename_skils_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/download.jpg', null=True, upload_to='static/images'),
        ),
    ]
