# Generated by Django 5.1.1 on 2025-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_alter_profile_profile_picture_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs_created',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_creators', to='employee_app.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=30),
        ),
    ]
