# Generated by Django 5.1.1 on 2025-02-05 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0011_user_jobs_created_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employee_applied',
            field=models.ManyToManyField(blank=True, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobs_created',
            field=models.ManyToManyField(blank=True, related_name='job_creators', to='employee_app.job'),
        ),
    ]
