# Generated by Django 5.1.1 on 2025-02-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0014_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs_created',
        ),
        migrations.AddField(
            model_name='user',
            name='jobs_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_creators', to='employee_app.job'),
            preserve_default=False,
        ),
    ]
