# Generated by Django 5.1.1 on 2025-02-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0015_remove_user_jobs_created_user_jobs_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jobs_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_creators', to='employee_app.job'),
        ),
    ]
