# Generated by Django 5.1.1 on 2025-02-06 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0016_alter_user_jobs_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs_created',
        ),
        migrations.AddField(
            model_name='job',
            name='jobs_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_creators', to=settings.AUTH_USER_MODEL),
        ),
    ]
