# Generated by Django 5.1.1 on 2025-02-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0018_user_applicants_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='applicants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to='employee_app.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=30),
        ),
    ]
