# Generated by Django 5.1.1 on 2025-02-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0020_remove_user_applicants_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applicants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to='employee_app.job'),
        ),
    ]
