# Generated by Django 5.1.1 on 2025-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0021_user_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='applicants',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=30),
        ),
    ]
