# Generated by Django 5.1.1 on 2025-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0022_remove_user_applicants_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='job_applicant', to='employee_app.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee')], max_length=30),
        ),
    ]
