# Generated by Django 5.1.1 on 2025-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0023_user_applicants_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=30),
        ),
    ]
