# Generated by Django 5.1.1 on 2025-02-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0024_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='applicants',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee')], max_length=30),
        ),
    ]
