# Generated by Django 5.1.1 on 2025-02-10 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0026_alter_user_role_job_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applicant',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
